---
- name: Database Setup
  hosts: 192.168.5.170
  remote_user: root
  roles:
    - common
    - database

- name: Webserver Setup
  hosts: 192.168.5.170
  remote_user: root
  roles:
    - common
    - web
    - php7
